name: Build

on:
  workflow_dispatch:
    # Inputs the workflow accepts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: Lafactorial/AnyKernel31
        ref: sweetk6a
        path: zipper

    - name: Android kernel build
      uses: Lafactorial/android-kernel-actions@master
      id: build
      env:
        NAME: MeMeDo
      with:
        arch: arm64
        compiler: clang/15
        defconfig: sweet_defconfig
        image: Image

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
          name: memedo
          path: kernel/
          compression-level: 0
